server:
  port: 8085
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数
    max-connections: 100 # 允许的最大连接数

feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合
hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      http-method-specify: true