server:
  port: 8084
  tomcat:
    threads:
      max: 50
    accept-count: 50
    max-connections: 100

feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

hm:
  db:
    database: hm-user
  swagger:
    title: 用户服务接口文档
    package: com.hmall.user.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m