server:
  port: 8086
  tomcat:
    threads:
      max: 50
    accept-count: 50
    max-connections: 100

feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

hm:
  swagger:
    title: 支付服务接口文档
    package: com.hmall.pay.controller
  db:
    database: hm-pay
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      http-method-specify: true
