server:
  port: 8082
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接

feign:
  okhttp:
    enabled: true # 开启 okhttp 功能
  sentinel:
    enabled: true # 开启 feign 对 sentinel 的支持

hm:
  db:
    database: hm-cart
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      http-method-specify: true # 开启请求方式前缀